#server port 설정
server:
  port: 9090

spring:
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: "YONEE001"
    password: "0000"

logging:
  level:
    "[com.jjang051.replyboard]": DEBUG

mybatis:
  mapper-locations: classpath:mapper/sqlmapper/**/*.xml
  config-location: classpath:mapper/config/config.xml
